# site setup
baseURL = "https://samui-samui.de/" # hostname & path to the root
defaultContentLanguage = "de"
disqusShortname = "samui-samui-de"
summaryLength = 70 # the length of text to show in a .Summary

# content particles
title = "Samui? Samui!"
copyright = "All rights reserved. Copyright samui-samui.de"
languageCode = "de-DE"
enableEmoji=true

# enable/disable functions
enableGitInfo = true # Enable GitInfo feature
enableRobotsTXT = true # Build robots.txt file
disableHugoGeneratorInject = true # Do not inject generator meta tag on homepage
watch = true # watch filesystem for changes and recreate as needed

# pagination
paginate = 5 # default 5 items per page
paginatePath = "seite"

rssLimit = 10

# see http://gohugo.io/templates/output-formats/
[outputs]
  home = [ "HTML", "RSS", "Algolia" ]
  page = [ "HTML" ]

[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true

[author]
name = "Patrick Kollitsch"
homepage = "https://samui-samui.de"

# see https://gohugo.io/content-management/urls/
[permalinks]
post = "/:year/:month/:title/"
page = "/:title/"

[taxonomies]
tag = "tags"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "lanczos"
# Defatult JPEG quality setting. Default is 75.
quality = 95
# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

[[menu.main]]
name = "Startseite"
weight = 1
identifier = "posts"
url = "/"
pre = "<i class='fas fa-home fa-fw'></i>"

[[menu.main]]
name = "Archiv"
weight = 100
identifier = "archiv"
url = "/archiv/"
pre = "<i class='fas fa-archive fa-fw'></i>"

[[menu.main]]
name = "Suchen"
weight = 200
identifier = "search"
url = "/suche/"
pre = "<i class='fas fa-search fa-fw'></i>"

[[menu.main]]
name = "Kontakt"
weight = 300
identifier = "kontakt"
url = "/kontakt/"
pre = "<i class='fas fa-envelope fa-fw'></i>"

[related]
threshold = 80 # Only include matches with rank >= threshold. 0 and 100.
includeNewer = true # adding newer articles to older ones (changing the content)
toLower = true # Will lower case keywords in both queries and in the indexes.

[[related.indices]]
name  = "tags"
weight = 100

[[related.indices]]
name  = "date"
weight = 10
pattern = "2006" # “200601” for busier times?

[params]
tagmanagerid = "GTM-P8XWV7K" # tagmanager container ID
version = "2018.1.159"

# social media setup
og_image = ""
og_image_url = ""
githubName = ""
twitterName =  ""

# content particles
siteslug = "samui-samui-de"
description = "Notizen über mein Leben als Auswanderer auf Koh Samui, Thailand"

# design elements
sitecolor = "#d02d19"


# AMP pages
amp = true # enables amp features

# define which amp-elements you are using globally, these elements will be included in every page
ampElements = ["amp-accordion","amp-ad","amp-analytics","amp-carousel","amp-iframe","amp-app-banner","amp-dynamic-css-classes","amp-form","amp-fx-flying-carpet","amp-image-lightbox","amp-lightbox","amp-sidebar","amp-social-share","amp-sticky-ad","amp-user-notification"]

themeColor = "#112233" # define a theme color (this will colorize the android address-bar)

adsensePublisher = "ca-pub-123456789" # required if you want to include google adsense
googleAnalytics = "UA-123456-78" # required if you want to use google analytics
appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content" # required if you want to add an app banner with iOS app
ampManifest = "/amp-manifest.json" # required if you want to add the app-banner feature

alternatePageName = "HUGO AMP" # alternative name for website structured data
organisationLogo = "https://gohugohq.com/logo.png" # set organisation logo for structured data
organisationName = "gohugohq.com" # set organisation name
organisationAddress = "Some Street 123, 12345 City" # set organisation address

socialProfiles = ["http://www.facebook.com/your-profile","http://instagram.com/yourProfile","http://www.linkedin.com/in/yourprofile","http://plus.google.com/your_profile"]  # for sameAs in organisation's structured data

publisherName = "gohugohq.com" # publisher used in article schema
publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
publisherLogoWidth = 600 # logo width
publisherLogoHeight = 60 # logo height

stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page

[params.social.facebook]
profileid = "517050641" # patrick.kollitsch
pageid = "6967849771" # samuisamui
appid = "2047624572136513" # samui-samui.de

[params.social.twitter]
profileid = "davidsneighbour"
siteid = "samui2"

# search setup
[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
